name: Test Secrets

on: 
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show Secrets
        run: |
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
