name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          # Copy files to the EC2 instance
          scp -o StrictHostKeyChecking=no -i key.pem -r ./ * $USER@$HOST:/home/ubuntu/password-generator-chrome-extension
